#cloud-config
network: {config: disabled}

hostname: dhcp-server
users:
  - name: aluno
    plain_text_passwd: "1234"
    lock_passwd: false
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]

write_files:
  - path: /etc/netplan/01-static.yaml
    permissions: '0644'
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          ens3:
            dhcp4: false
            addresses: [192.168.122.10/24]
            gateway4: 192.168.122.1
            nameservers:
              addresses: [8.8.8.8, 1.1.1.1]

  - path: /etc/dhcp/dhcpd.conf
    permissions: '0644'
    content: |
      subnet 192.168.122.0 netmask 255.255.255.0 {
        range 192.168.122.100 192.168.122.200;
        option routers 192.168.122.10;
        option domain-name-servers 8.8.8.8;
        default-lease-time 600;
        max-lease-time 7200;
      }

  - path: /etc/default/isc-dhcp-server
    permissions: '0644'
    content: |
      INTERFACESv4="ens3"
      INTERFACESv6=""

  - path: /usr/local/bin/setup-dhcp.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      apt-get update
      apt-get install -y isc-dhcp-server net-tools
      systemctl enable isc-dhcp-server
      systemctl restart isc-dhcp-server
      ufw disable
      echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
      sysctl -p

runcmd:
  - netplan apply
  - bash /usr/local/bin/setup-dhcp.sh
