#cloud-config
hostname: dhcp-client
users:
  - name: aluno
    plain_text_passwd: "1234"
    lock_passwd: false
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]

write_files:
  - path: /usr/local/bin/request-ip.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      apt-get update
      apt-get install -y isc-dhcp-client net-tools
      iface=$(ip link | awk -F: '$0 ~ "^[0-9]+: ens" {print $2}' | tr -d ' ')
      dhclient -v $iface

runcmd:
  - bash /usr/local/bin/request-ip.sh
